# Name of Your Workflow
name: My Test Workflow

# Define the trigger events
on: [push]

# Job run in parallel by default, each run steps in sequence
jobs: 

    # Job 1 to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, GitHub Actions!"
          
    # Job 2 to build and test our C code
    test-c-code:
        needs: [say-hello]
        runs-on: ubuntu-latest
        steps:
        
        # Use github.com/action/checkouy to check out this repo
          - name: Check out this repo
            uses: actions/checkout@v3
            
            # Install necessary-packages
          - name: Install dependencies
            run: sudo apt install -y build-essential python3
            
            # Posting what the active directory is
          - run: pwd

            # Run our test
          - name: Run test
            run: python3 test.py