# Name of Your Workflow
name: My Test Workflow

# Define the trigger events
on: [push]

# Job run in parallel by default, each run steps in sequence
jobs: 

    # Job to print something out
    say-hello:
        runs-on: ubuntu-latest
        steps:
          - run: echo "Hello, GitHub Actions!"
          
    # Job to build and test our C code
    needs: [say-hello]
    runs-on: ubuntu-latest
    steps:
    
    # Use github.com/action/checkouy to check out this repo
      - name: Check out this repo
        uses: actions/checkout@v3
        
        # Install necessary-packages
      - name: Install dependencies
        run: sudo apt install -y build-essential python3
        
        # Run our test
      - name: Run test
        run: python3 test.py